# Generated by Django 5.2.13 on 2026-04-18 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_seasonal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nutritionist', models.ForeignKey(limit_choices_to={'role': 'nutritionist'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_plans', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Petit-déjeuner'), ('lunch', 'Déjeuner'), ('dinner', 'Dîner'), ('snack', 'Collation')], max_length=20)),
                ('food_name', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=100)),
                ('calories', models.IntegerField(help_text='Calories estimées')),
                ('order', models.IntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='nutritionists.dietplan')),
            ],
            options={
                'ordering': ['plan', 'meal_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('patient_assigned', 'Nouveau patient'), ('consultation_reminder', 'Rappel consultation'), ('new_message', 'Nouveau message'), ('plan_updated', 'Plan mis à jour')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('related_id', models.IntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nutritionist', models.ForeignKey(limit_choices_to={'role': 'nutritionist'}, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('nutritionist', models.ForeignKey(limit_choices_to={'role': 'nutritionist'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_patients', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_nutritionist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('nutritionist', 'patient')},
            },
        ),
        migrations.CreateModel(
            name='PatientMealChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'À faire'), ('completed', 'Fait'), ('skipped', 'Sauté')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutritionist_meal_checklists', to='nutritionists.meal')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_checklists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'meal__meal_type', 'meal__order'],
                'unique_together': {('patient', 'meal', 'date')},
            },
        ),
    ]
