# Generated by Django 5.2.13 on 2026-04-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmealchecklist',
            name='meal_time',
            field=models.CharField(default='12:00', help_text='Heure du repas (ex: 08:00, 12:30)', max_length=20),
        ),
    ]
