# Generated by Django 5.2.14 on 2026-05-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialoffer',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
