# Generated by Django 5.2.14 on 2026-05-23 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionists', '0002_specialoffer_extra_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientmealchecklist',
            options={'ordering': ['date', 'meal_time']},
        ),
        migrations.AlterUniqueTogether(
            name='patientmealchecklist',
            unique_together={('patient', 'meal_name', 'date')},
        ),
        migrations.AddField(
            model_name='patientmealchecklist',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patientmealchecklist',
            name='meal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nutritionist_meal_checklists', to='nutritionists.meal'),
        ),
    ]
