# Generated by Django 5.2.13 on 2026-04-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionists', '0002_patientmealchecklist_meal_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmealchecklist',
            name='meal_name',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
