# Generated by Django 5.2.13 on 2026-04-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionists', '0003_patientmealchecklist_meal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('patient_assigned', 'Nouveau patient'), ('consultation_reminder', 'Rappel consultation'), ('new_message', 'Nouveau message'), ('plan_updated', 'Plan mis à jour'), ('blog_pending', 'Blog Pending'), ('blog_update', 'Blog Update')], max_length=50),
        ),
    ]
