# Generated by Django 5.2.13 on 2026-04-25 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionists', '0005_patientprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('discount_percent', models.IntegerField(default=0)),
                ('offer_type', models.CharField(choices=[('diet_plan', 'Diet Plan'), ('seasonal', 'Seasonal Offer')], default='diet_plan', max_length=20)),
                ('valid_until', models.DateField()),
                ('image_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diet_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nutritionists.dietplan')),
            ],
        ),
    ]
