# Generated by Django 5.2.13 on 2026-04-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionists', '0006_specialoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialoffer',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='features',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='icon',
            field=models.CharField(default='🍽️', max_length=10),
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='short_description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
