# Generated by Django 5.2.13 on 2026-04-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionists', '0009_specialoffer_duration_days_patientsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientsubscription',
            name='duration_months',
            field=models.IntegerField(default=1),
        ),
    ]
