# Generated by Django 5.2.13 on 2026-05-02 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionists', '0010_patientsubscription_duration_months'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('patient_assigned', 'Nouveau patient'), ('consultation_reminder', 'Rappel consultation'), ('new_message', 'Nouveau message'), ('plan_updated', 'Plan mis à jour'), ('blog_pending', 'Blog Pending'), ('blog_update', 'Blog Update'), ('assignment_request', "Demande d'assignation"), ('assignment_approved', 'Assignation approuvée'), ('assignment_rejected', 'Assignation refusée'), ('admin_notification', 'Notification Admin')], max_length=50),
        ),
        migrations.CreateModel(
            name='AssignmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Refusé')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nutritionist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_requests_received', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('patient', 'nutritionist')},
            },
        ),
    ]
