# Generated by Django 5.2.13 on 2026-05-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionists', '0011_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Refusé'), ('cancelled', 'Annulé')], default='pending', max_length=20),
        ),
    ]
