# Generated by Django 5.2.13 on 2026-04-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_foodlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='payment_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_plan',
            field=models.CharField(choices=[('free', 'Free (Blog only)'), ('standard', 'Standard Plan - Diet & AI'), ('premium', 'Premium Plan - Full Access')], default='free', max_length=20),
        ),
    ]
