# Generated by Django 5.2.13 on 2026-04-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_payment_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='downloaded_plan_pdf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_ai_tracker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_consultations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_diet_plan',
            field=models.BooleanField(default=False),
        ),
    ]
