"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import redis

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-k9fj^*h1#0qtf4eg5=ta2a25wz8oks(f80e+b9z1)duapupgmu'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'nutrition', 

    'rest_framework',
    'corsheaders',
    'payments',
    'blog',
    'consultations',
    'notifications',
    'email_notifications',
    'admin_dashboard',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
CORS_ALLOW_ALL_ORIGINS = True

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = 'ramdaninourhane26@gmail.com'
EMAIL_HOST_PASSWORD = 'twrr sbxz ctcr gvbp'
CELERY_BROKER_URL = "redis://default:96MvqT34dcxzcdLYvpXzNswJCNOoYOm7@redis-16568.c341.af-south-1-1.ec2.cloud.redislabs.com:16568/0"

CELERY_RESULT_BACKEND = "redis://default:96MvqT34dcxzcdLYvpXzNswJCNOoYOm7@redis-16568.c341.af-south-1-1.ec2.cloud.redislabs.com:16568/0"
JAZZMIN_SETTINGS = {

    # 🏷️ Branding (Nutrition Project)
    "site_title": "NutriLife | Nutrition Dashboard",
    "site_header": "NutriLife Admin Panel",
    "site_brand": "NutriLife 🥗",

    # 👋 Welcome message
    "welcome_sign": "Welcome Nourhane serine💚 | Manage Nutrition System",

    # 🎨 Icons & UI
    "site_icon": "fas fa-apple-alt",
    "site_logo_classes": "img-circle",



    # 🔎 Search models (nutrition context)
    "search_model": [
        "auth.User",
        "nutrition.Food",
        "nutrition.DietPlan",
        "nutrition.Meal",
        "notifications.Notification",
    ],

    # 📌 Top menu (important pages)
    "topmenu_links": [
        {"name": "Dashboard", "url": "admin:index"},
        {"model": "auth.User"},
        {"model": "nutrition.Food"},
        {"app": "nutrition"},
        {"app": "notifications"},
    ],

    # 📊 Sidebar settings
    "show_sidebar": True,
    "navigation_expanded": True,

    # 🍎 Icons per app (Nutrition themed)
    "icons": {
        "auth": "fas fa-users",
        "auth.user": "fas fa-user",

        "nutrition": "fas fa-utensils",
        "nutrition.food": "fas fa-apple-alt",
        "nutrition.dietplan": "fas fa-clipboard-list",
        "nutrition.meal": "fas fa-bread-slice",

        "notifications": "fas fa-bell",
    },

    # ⚙️ UI behavior
    "show_ui_builder": False,

    # 🧾 Footer (PFE important)
    "copyright": "NutriLife © 2026 | Nutrition Management System by Nourhane serine",
}
JAZZMIN_UI_TWEAKS = {

    # 🎨 Sidebar color (GREEN nutrition style 🥗)
    "sidebar_bg": "bg-success",

    # 🟢 Navbar color
    "navbar": "navbar-success",

    # 🎯 Accent color (buttons, highlights)
    "accent": "accent-primary",

    # 📌 Layout clean
    "navbar_small_text": False,
    "sidebar_nav_small_text": False,

    # 🌙 Modern feel
    "theme": "flatly",
}