# Generated by Django 5.2.14 on 2026-05-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
