# Generated by Django 5.2.13 on 2026-05-01 17:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_alter_consultation_options_consultation_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='is_trial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultation',
            name='trial_confirmation_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='nutritionist_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
