# Generated by Django 5.2.13 on 2026-04-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(default='articles', max_length=50),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(default='', help_text='Résumé court pour la carte'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='featured_image',
            field=models.URLField(blank=True, help_text="URL de l'image"),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='read_time',
            field=models.CharField(default='5 min read', max_length=20),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.CharField(default='NutriLife Team', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(help_text="Contenu complet de l'article"),
        ),
    ]
