# Generated by Django 5.2.13 on 2026-04-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_category_blogpost_excerpt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('draft', 'Brouillon'), ('published', 'Publié'), ('rejected', 'Refusé')], default='draft', max_length=20),
        ),
    ]
